### PR TITLE
Automod

### PR DESCRIPTION
**Pull request by Cu3t0m**
Commands:
- filter
- filter add (word)
- filter remove (word)
- filter ignore (word)
- filter ignore
- filter list

Note: the command filter toggles the automod, the bot also needs manage message and create webhook permissions for it to work.

### CODE REVIEW

**Comment by MhmCats** [comment]
This just looks like it has been copied from [here](https://github.com/BobDotCom/BobDotBot/blob/main/cogs/filter.py).

**Comment by Cu3t0m** [comment]
hehe but i forgot to add credits

**Comment by Cu3t0m** [comment]
i thought u could after i saw a file that was from the nextcord/previous bot in here

**Comment by Cu3t0m** [comment]
thnk it was the rtfm cog

**Comment by MhmCats** [comment]
You do have to follow a project's LICENSE...

**Pull request closed without merging**
